name: example
description: "A new Flutter project."
publish_to: 'none'
version: 0.1.0

resolution: workspace

environment:
  sdk: '>=3.5.0 <4.0.0'

dependencies:
  flutter:
    sdk: flutter

  mapkit_lite_extension: 
    path: ../

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: any

flutter:
  uses-material-design: true
