name: mapkit_lite_extension
description: >- 
 Expands YandexMapLite capabilities and brings a convenient API.
version: 0.1.0
repository: https://github.com/AndreyKedo/mapkit_lite_extension

publish_to: none

workspace: 
  - example

environment:
  sdk: '>=3.5.0 <4.0.0'
  flutter: ">=3.24.0"

dependencies:
  flutter:
    sdk: flutter
  flutter_svg: ^2.1.0
  collection: ^1.19.1
  uuid: ^4.5.1
  fluster: ^1.2.0
  # Fix issue https://github.com/surfstudio/yandex-mapkit-lite-flutter/issues/25
  yandex_mapkit_lite:
    git:
      url: https://github.com/waslost0/yandex-mapkit-lite-flutter.git
      ref: main
  async: ^2.12.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: any